
<div class="container-fluid gtco-testimonials">
  <div class="container">
   <h2>NOSSOS CLIENTES</h2>
   <div class="owl-carousel owl-carousel1 owl-theme">
    <?php 
    for($i=1;$i< 15;$i++){
     ?>
     <div>
       <div class="card text-center"><img class="card-img-top" src="INDEX/images/customer1.jpg" alt="">
        <div class="card-body">
         <h5>Maria Souza <?=$i?> <br/>
          <span> Estudante <?=$i?> </span></h5>
          <p class="card-text">“ Muito top, já recupei o dinheiro investido em menos de 2 meses ” </p>
        </div>
      </div>
    </div>

    <?php
  }
  ?>


</div>
</div>
</div>
