
    <footer class="container-fluid" id="gtco-footer">
     <div class="container">
      <div class="col-12" id="contact">
       <h4>FALE CONOSCO</h4>
       <input type="text" class="form-control" placeholder="Seu nome">
       <input type="email" class="form-control" placeholder="Email válido">
       <textarea class="form-control" placeholder="Mensagem"></textarea>
       <a href="#" class="submit-button pull-rigth">ENVIAR <i class="fa fa-angle-right" aria-hidden="true"></i></a>
      </div>
     </div>
    </footer>