<nav class="navbar navbar-expand-lg navbar-light bg-light bg-transparent" id="gtco-main-nav">
  <div class="container">
    <a class="navbar-brand">CAPITAL RETORN</a>
    <button class="navbar-toggler" data-target="#my-nav" onclick="myFunction(this)" 
    data-toggle="collapse">
    <span class="bar1"></span> 
    <span class="bar2"></span> 
    <span class="bar3"></span>
  </button>

  <div id="my-nav" class="collapse navbar-collapse">
   <ul class="navbar-nav mr-auto">
    <li class="nav-item"><a class="nav-link" href="#">HOME</a></li>
    <li class="nav-item"><a class="nav-link" href="#services">EMPRESA</a></li>
    <li class="nav-item"><a class="nav-link" href="#contact">FALE CONOSCO</a></li>
  </ul>
  <form class="form-inline my-2 my-lg-0">
    <a href="#" class="btn btn-info my-2 my-sm-0 text-uppercase" data-toggle="modal" 
    data-target="#modalogin">LOGIN</a>
  </form>
</div>
</div>
</nav>
<div class="container-fluid gtco-banner-area">
 <div class="container">
  <div class="row">
    <div class="col-md-8">
    <h1>Investimento
      em ações núcleo 
      <span>AS INTOCÁVEIS</span>
    </h1>
    <p>A bolsa de valores oferece inúmeras oportunidades de investimento para quem está à
    procura de investimentos com maior potencial de valorização. </p>
    <a href="#" class='cadastro'>EU QUERO<i class="fa fa-angle-right" aria-hidden="true"></i></a>

  </div>
  <div class="col-md-4">
    <img class="card-img-top img-fluid" src="INDEX/images/banner-img.png" alt="">

  </div>
</div>
</div>
</div>